# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "多模信息感知与视觉导航实验室"
title:              "Multimodal Information Perception and Visual Navigation Lab at the Beihang University"
description:        "The Kording Lab is a computational neuroscience and causality research group at the University of Pennsylvania."
#新建主题
theme: minima


# URL
url:                http://kordinglab.com
baseurl:            
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title.html

# Markdown
markdown:           kramdown

# Highlighter
highlighter:        rouge

# Navigation
nav:
  - name:           "home"
    href:           "/"
  - name:           "about"
    href:           "/about"
  - name:           "publications"
    href:           "/publication"
  - name:           "people"
    href:           "/people"
  - name:           "pictures"
    href:           "/pictures"
#   - name:           "abstracts"
#     href:           "/abstracts"
  - name:           "lab teachings"
    href:           "/presentations"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
  -
    scope:
      path:         ""
      type:         "people"
    values:
      layout:       "profile"


collections:
  people:
    output: true
    permalink: /people/:title/index.html
